version: "3"
services:          
    mysql:

        image: mysql:5
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: HandsOnTest
        ports:
            - "3306:3306"

    ratingmodeler:
        image: ratingmodelercsv:latest
        container_name: ratingmodelercsv
        environment:
            MODE: mysql
            FILE_PATH: /opt/RatingModelerCSV/ratings2.csv
            IP: mysql:3306
networks:
    default:
        external:
            name: handsOnNet
