apiVersion: v1
kind: Service
metadata:
  name: cigo-zookeeper
  labels:
    app: cigo-zookeeper
spec:
  ports:
  - name: "client"
    port: 32181
    targetPort: 32181
  - name: "server"
    port: 2888
    targetPort: 2888
  - name: "leader"
    port: 3888
    targetPort: 3888
  clusterIP: None
  selector:
    app: cigo-zookeeper
---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  labels:
    app: cigo-zookeeper
  name: cigo-zookeeper
spec:
  selector:
    matchLabels:
      app: cigo-zookeeper 
  serviceName: cigo-zookeeper
  replicas: 3
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: cigo-zookeeper
    spec:
      containers:
      - env:
        - name: DB_HOST
          value: 127.0.0.1:3306
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cloudsql-db-credentials
              key: password
        - name: ZOOKEEPER_CLIENT_PORT
          value: "32181"
        - name: ZOOKEEPER_SERVER_PORT
          value: "2888"
        - name: ZOOKEEPER_LEADER_PORT
          value: "3888"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
        - name: ZOOKEEPER_REPLICA_COUNT
          value: "3"
        image: sparsitytechnologies/cigo-zookeeper:0.1
        name: cp-zookeeper
        ports:
        - containerPort: 32181
        - containerPort: 2888
        - containerPort: 3888

      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.11
        command: ["/cloud_sql_proxy",
                  "-instances=buoyant-episode-216912:europe-west1:mysql-share=tcp:3306",
                  "-credential_file=/secrets/cloudsql/credentials.json"]
        volumeMounts:
          - name: cloudsql-instance-credentials
            mountPath: /secrets/cloudsql
            readOnly: true

      volumes:
          - name: cloudsql-instance-credentials
            secret:
              secretName: cloudsql-instance-credentials
      restartPolicy: Always
