apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kibana-ing
spec:
  backend:
    serviceName: kibana
    servicePort: 5601
---          
apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    app: kibana
spec:
  type: NodePort 
  ports:
  - name: "server"
    port: 5601
  selector:
    app: kibana
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  labels:
    app: kibana
  name: kibana
spec:
  selector: 
    matchLabels:
      app: kibana
  serviceName: kibana
  replicas: 1
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
      - image: docker.elastic.co/kibana/kibana:5.6.3
        name: kibana
        ports:
        - containerPort: 5601
        resources: {}
      restartPolicy: Always
