apiVersion: batch/v1
kind: Job 
metadata:
  name: cigo-init
spec:
  template:
    metadata:
      labels:
        name: cigo-init
    spec:
      containers:
      - env:
        - name: SCHEMA_REGISTRY_HOST_NAME
          value: cigo-schema-registry
        - name: SCHEMA_REGISTRY_PORT
          value: "8081"
        - name: DATA_MODEL_REPOSITORY
          value: https://github.com/My-TRAC/data-model 
        - name: CONFIGURATION_SCRIPTS
          value: https://github.com/My-TRAC/ConfigurationScripts.git
        - name: CONNECT_BOOTSTRAP_SERVERS
          value:  cigo-kafka:29092
        - name: TOPICS
          value: "ratings, CigoJdbcActivitiesSummary"
        - name: KAFKA_CONNECT_HOST
          value: cigo-kafka-connect
        image: sparsitytechnologies/cigo-init:0.1
        name: cigo-init
        resources: {}
      restartPolicy: Never
  backoffLimit: 4
status: {}
