apiVersion: v1
kind: Service
metadata:
  name: cigo-schema-registry
  labels:
    name: cigo-schema-registry
spec:
  ports:
  - name: "listener"
    port: 8081
    targetPort: 8081
  clusterIP: None
  selector:
    name: cigo-schema-registry
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cigo-schema-registry
spec:
  replicas: 3
  strategy: {}
  template:
    metadata:
      labels:
        name: cigo-schema-registry
    spec:
      containers:
      - env:
        - name: SCHEMA_REGISTRY_HOST_NAME
          value: cigo-schema-registry 
        - name: SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL
          value: cigo-zookeeper.default.svc.cluster.local:32181
        - name: SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL
          value: PLAINTEXT
        - name: SCHEMA_REGISTRY_TOPIC_REPLICATION_FACTOR
          value: "3"
        - name: SCHEMA_REGISTRY_LISTENERS
          value: http://cigo-schema-registry.default.svc.cluster.local:8081
        image: sparsitytechnologies/cigo-schema-registry:0.1
        name: schema-registry
        ports:
        - containerPort: 8081
        resources: {}
      restartPolicy: Always
status: {}
