---
apiVersion: v1
kind: Service
metadata:
  name: cigo-schema-registry-svc
  labels:
    name: cigo-schema-registry-svc
spec:
  ports:
  - name: "listener"
    port: 8081
    targetPort: 8081
  clusterIP: None
  selector:
    name: cigo-schema-registry
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cigo-schema-registry
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        name: cigo-schema-registry
    spec:
      containers:
      - env:
        - name: SCHEMA_REGISTRY_HOST_NAME
          value: cigo-schema-registry-svc 
        - name: SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL
          value: cigo-zookeeper-svc.default.svc.cluster.local:32181
        - name: SCHEMA_REGISTRY_LISTENERS
          value: http://cigo-schema-registry-svc.default.svc.cluster.local:8081
        image: confluentinc/cp-schema-registry:4.0.0
        name: schema-registry
        ports:
        - containerPort: 8081
        resources: {}
      restartPolicy: Always
status: {}
