apiVersion: batch/v1
kind: Job 
metadata:
  name: cigo-init
spec:
  template:
    metadata:
      labels:
        name: cigo-init
    spec:
      containers:
      - env:
        - name: SCHEMA_REGISTRY_HOST_NAME
          value: cigo-schema-registry
        - name: SCHEMA_REGISTRY_PORT
          value: "8081"
        - name: DATA_MODEL_REPOSITORY
          value: https://github.com/My-TRAC/data-model 
        image: sparsitytechnologies/cigo-init:latest
        name: cigo-init
        resources: {}
      restartPolicy: Never
  backoffLimit: 4
status: {}
