apiVersion: v1
kind: Service
metadata:
  name: cigo-kafka-svc
  labels:
    app: cigo-kafka-svc
spec:
  ports:
  - name: "listener"
    port: 29092
    targetPort: 29092
  clusterIP: None
  selector:
    app: cigo-kafka
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  labels:
    app: cigo-kafka
  name: cigo-kafka
spec:
  serviceName: cigo-kafka-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: cigo-kafka
    spec:
      containers:
      - env:
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: cigo-zookeeper-0.cigo-zookeeper-svc.default.svc.cluster.local:32181
        image: confluentinc/cp-kafka:4.0.0
        name: kafka
        ports:
        - containerPort: 29092
        command:
        - /bin/bash
        - -c
        - export KAFKA_BROKER_ID=$((${HOSTNAME##*-}+1)) && export KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://cigo-kafka-${HOSTNAME##*-}.cigo-kafka-svc.default.svc.cluster.local:29092 && /etc/confluent/docker/run
        resources: {}
      restartPolicy: Always
status: {}
