apiVersion: v1
kind: Service
metadata:
  name: cigo-kafka
  labels:
    app: cigo-kafka
spec:
  ports:
  - name: "listener"
    port: 29092
    targetPort: 29092
  clusterIP: None
  selector:
    app: cigo-kafka
---
apiVersion: apps/v1beta2
kind: StatefulSet
metadata:
  labels:
    app: cigo-kafka
  name: cigo-kafka
spec:
  selector:
    matchLabels:
      app: cigo-kafka 
  serviceName: cigo-kafka
  replicas: 1
  template:
    metadata:
      labels:
        app: cigo-kafka
    spec:
      containers:
      - env:
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_LISTERNER_PORT
          value: "29092"
        - name: ZOOKEEPER_REPLICA_COUNT
          value: "1"
        - name: ZOOKEEPER_PORT
          value: "32181"
        image: sparsitytechnologies/cigo-kafka:latest
        name: kafka
        ports:
        - containerPort: 29092
        resources: {}
      restartPolicy: Always
