apiVersion: v1
kind: Service
metadata:
  name: gtfsloader-svc
  labels:
    app: gtfsloader-svc
spec:
  type: LoadBalancer 
  ports:
  - name: "server"
    port: 4567 
  selector:
    app: gtfsloader
status:
  loadBalancer: {}
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  labels:
    app: gtfsloader
  name: gtfsloader
spec:
  serviceName: gtfsloader-svc
  replicas: 1
  template:
    metadata:
      labels:
        app: gtfsloader
    spec:
      containers:
      - env:
        - name: MYSQL_HOST
          value: mysql-svc.default.svc.cluster.local 
        - name: KAFKA_CONNECT_HOST
          value: cigo-kafka-connect-svc.default.svc.cluster.local
        image: sparsitytechnologies/gtfsloader:latest
        name: gtfsloader 
        ports:
        - containerPort: 4567
      restartPolicy: Always
status: {}
