version: "3"
services:          
    mysql_ratingmodeler:
        image: mysql:5.7
        container_name: mysql_ratingmodeler
        environment:
            MYSQL_ROOT_PASSWORD: confluent
            MYSQL_USER: confluent
            MYSQL_PASSWORD: confluent
            MYSQL_DATABASE: connect_test
    ratingmodeler:
        image: sparsitytechnologies/ratingmodeler:latest
        #image: ratingmodeler:latest
        container_name: ratingmodeler
        depends_on:
            - mysql_ratingmodeler
        environment:
            KAFKA_CONNECT_HOST: kafka-connect
            SCHEMA_REGISTRY_HOST_NAME: schema-registry
            MYSQL_HOST: mysql_ratingmodeler
            MYSQL_DATABASE: connect_test
            MYSQL_USER: confluent
            MYSQL_PASSWORD: confluent
            ELASTIC_TOPICS: "cigo-jdbc-activities_summary, ratings"
            SINK_TOPICS: "ratings"
networks:
    default:
        external:
            name: cigo-compose_default

            #volumes:
            #    mysql_ratingmodeler:
