version: "3"
services:          
    mysql_ratingmodeler:
        image: mysql:5.5.59
        container_name: mysql_ratingmodeler
        environment:
            MYSQL_ROOT_PASSWORD: confluent
            MYSQL_USER: confluent
            MYSQL_PASSWORD: confluent
            MYSQL_DATABASE: connect_test
            #        depends_on:
            #- kafka-connect
            #volumes:
            #- mysql_ratingmodeler:/var/lib/mysql
            #ports:
            #- 3307:3306
    ratingmodeler:
        image: sparsitytechnologies/ratingmodeler:latest
        #image: ratingmodeler:latest
        container_name: ratingmodeler
        depends_on:
            - mysql_ratingmodeler
              #        ports:
              #            - "4567:4567"
        environment:
            KAFKA_CONNECT_HOST: kafka-connect
            MYSQL_HOST: mysql_ratingmodeler
            MYSQL_PASSWORD: confluent
            ELASTIC_TOPICS: "cigo-jdbc-activities_summary"
            SINK_TOPICS: "ratings"
networks:
    default:
        external:
            name: cigo-compose_default

            #volumes:
            #    mysql_ratingmodeler:
