version: "3"
services:          
    mysql:
        image: mysql:5.5.59
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: confluent
            MYSQL_USER: confluent
            MYSQL_PASSWORD: confluent
            MYSQL_DATABASE: connect_test
            #        depends_on:
            #- kafka-connect
    ratingmodeler:
        #image: sparsitytechnologies/ratingmodeler:latest
        image: ratingmodeler:latest
        container_name: ratingmodeler
        depends_on:
            - mysql
        ports:
            - "4567:4567"
        environment:
            KAFKA_CONNECT_HOST: kafka-connect
            MYSQL_HOST: mysql
            ELASTIC_TOPICS: "cigo-jdbc-trips, cigo-jdbc-stops,cigo-jdbc-routes,cigo-jdbc-stop_times,cigo-jdbc-calendar_dates,cigo-jdbc-calendar,cigo-jdbc-frequencies,cigo-jdbc-transfers,cigo-jdbc-agency,cigo-jdbc-cigo-jdbc-feed_info,cigo-jdbc-shapes"
            SINK_TOPICS: "ratings"
networks:
    default:
        external:
            name: cigo-compose_default
